import { format } from 'date-fns';

export default function generateTemplate(position, company) {
	const name = process.env.NAME;
	const phone = process.env.PHONE;
	const email = process.env.EMAIL;
	const date = format(Date.now(), 'LLLL d, yyyy');
	const template = `
${name}
${phone}
${email}
${date}
\nTo whom it may concern,
\nI'm interested in the ${position} position at ${company}. \
As someone who is highly focused and attentive to detail, \
I enjoy building quality, end-to-end systems that users enjoy. \
I'd like the opportunity to apply my technical expertise as part of ${company}'s team.
\nWhile experienced in various languages and technologies, I have primarily been developing in \
JavaScript for Web Development. \
I like to optimize my processes and abstract away redundancies. \
For example, this very cover letter was generated by a program I wrote to save \
time when applying to jobs. It was generated in one command.
\nI recently started a blog, www.ahmedjahmi.com where I share what I learn. \
Aside from sharing, the blog itself is an ongoing learning lesson and example of my skillset. \
The project is a fullstack application built with Next.js, MongoDB, Auth0 and Cloudinary. \
Users are able to signup and edit their profiles. They can leave comments or like and share posts. \
I included role based authorization for admin purposes, as well as \
SEO and Google analytics optimizations.
\nThank you for your time and consideration. I'm looking forward to learning more \
details about the ${position} position at ${company}. \
I'm excited about the opportunity to leverage my unique range of skills, \
and I'm eager to demonstrate my commitment to developing world-class software solutions for ${company}. \

\nSincerely,
Ahmed Jahmi.
  `;
	return template;
}
